version: '3'
services:
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    image: node:6.9.1
    working_dir: /work
    volumes:
      - .:/work
    ports:
      - "3000:3000"
    command: "npm start"

  test:
    image: postman/newman
    working_dir: /work
    volumes:
      - .:/work
    command: "newman run your_postman_collection.json"

volumes:
  mongo-data:
