version: '3'
services:
  db:
    image: mongo:4.2
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    image: node:6.9.1
    container_name: node_web
    working_dir: /work
    volumes:
      - .:/work
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db

  test:
    image: postman/newman:alpine
    container_name: newman_test
    volumes:
      - .:/etc/newman
    command: run /etc/newman/postman_collection.json
    depends_on:
      - web

volumes:
  mongo_data:

