version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: node-web
    ports:
      - "3000:3000"
    depends_on:
      - db

  test:
    image: postman/newman:latest
    container_name: newman-test
    volumes:
      - ./postman-collection:/etc/newman
    depends_on:
      - web
    command: ["run", "/etc/newman/your-collection.json"]

volumes:
  mongo-data:

